module.exports = {
    DATA: { INPUT_PATH: '', DUMMY_SIZE: 1024 * 1024 * 16 },
    PROTOCOL: { MAGIC_BYTE: 0xAA, VERSION: 0x01, HEADER_SIZE: 8, PIECE_COUNT: 64 },
    TRANSCODE: { PIECE_COUNT: 64, PIECE_SIZE: 1024, SYSTEMATIC: true },
    NETWORK: { LOSS_RATE: 0.1, REDUNDANCY: 1.5, LATENCY: 5, JITTER: 2 },
    WINDOW: { SIZE: 8, TIMEOUT: 1000 },
    SYSTEM: { TARGET_THROUGHPUT_MB: 50, TICK_RATE: 20 }
};
