module.exports = {
    DATA: { INPUT_PATH: '', DUMMY_SIZE: 1024 * 1024 * 2 },
    PROTOCOL: { MAGIC_BYTE: 0xAA, VERSION: 0x01, HEADER_SIZE: 8, PIECE_COUNT: 16 },
    TRANSCODE: { PIECE_COUNT: 16, PIECE_SIZE: 1024, SYSTEMATIC: true },
    NETWORK: { LOSS_RATE: 0.15, REDUNDANCY: 2.0, LATENCY: 20, JITTER: 5 },
    WINDOW: { SIZE: 8, TIMEOUT: 1000 },
    SYSTEM: { TARGET_THROUGHPUT_MB: 5, TICK_RATE: 50, THREADS: 2, GLOBAL_TIMEOUT: 60000 }
};
