module.exports = {
    DATA: { INPUT_PATH: '', DUMMY_SIZE: 1024 * 1024 * 1 },
    PROTOCOL: { MAGIC_BYTE: 0xAA, VERSION: 0x01, HEADER_SIZE: 8, PIECE_COUNT: 16 },
    TRANSCODE: { PIECE_COUNT: 64, PIECE_SIZE: 1024, SYSTEMATIC: true },
    NETWORK: {
        LOSS_RATE: 0.0,
        REDUNDANCY: 1.5,
        LATENCY: 0,
        JITTER: 0,
        PEER_ADDRESS: '127.0.0.1',
        PEER_PORT: 46642,
        UNIDIRECTIONAL: true
    },
    WINDOW: { SIZE: 8, TIMEOUT: 1000 },
    SYSTEM: { TARGET_THROUGHPUT_MB: 5, TICK_RATE: 20, THREADS: 1, GLOBAL_TIMEOUT: 60000 }
};
